name = "pinterest-oauth-worker"
main = "src/index.ts"
compatibility_date = "2024-04-03"

# Add a placeholder for the KV namespace.
# The user will need to create a KV namespace called "PINTEREST_OAUTH_KV"
# and add its id to this file.
[[kv_namespaces]]
binding = "PINTEREST_OAUTH_KV"
id = "356fc26fdd404b6ea3a5f7d50c129fff"
